openapi: 3.0.0
info:
  title: Grove Backend
  description: |-
    This is the OpenAPI spec defining the data and queries that the Grove database can return. See our whole project at [our project site](https://groveapp.github.io). For
        this sample, you can use the api key `special-key` to test the authorization     filters.
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
externalDocs:
  description: Find out more about Grove
  url: http://groveapp.github.io
servers:
- url: https://localhost:8000
- url: https://virtserver.swaggerhub.com/grove1/grove_backend/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: citizen
  description: Everything related to citizen (user) data
- name: leader
  description: Everything related to leaders
- name: issues
  description: Issue pages
- name: viewpoint
  description: Viewpoint data
- name: organization
  description: Organizations
paths:
  /organization:
    put:
      tags:
      - pet
      summary: Update an existing organization
      operationId: updateOrg
      requestBody:
        $ref: '#/components/requestBodies/Organization'
      responses:
        "400":
          description: Invalid ID supplied
        "405":
          description: Validation exception
      security:
      - grove_auth:
        - write:viewpoints
        - read:viewpoints
      x-swagger-router-controller: Pet
    post:
      tags:
      - organization
      summary: Add a new organization
      operationId: addOrg
      requestBody:
        $ref: '#/components/requestBodies/Organization'
      responses:
        "405":
          description: Invalid input
      security:
      - grove_auth:
        - write:viewpoints
        - read:viewpoints
      x-swagger-router-controller: Organization
  /issue:
    get:
      tags:
      - issue
      summary: Finds issues by id
      description: Muliple tags can be provided with comma separated strings. Use\
        \ tag1, tag2, tag3 for testing.
      operationId: getIssuesByID
      parameters:
      - name: ids
        in: query
        description: ids
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
        "400":
          description: Invalid
      deprecated: true
      security:
      - grove_auth:
        - write:viewpoints
        - read:viewpoints
      x-swagger-router-controller: Issue
    post:
      tags:
      - issue
      summary: Add a new issue
      operationId: addIssue
      requestBody:
        $ref: '#/components/requestBodies/Issue'
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Issue
  /viewpoint:
    get:
      tags:
      - viewpoint
      summary: Finds viewpoints by id
      description: Muliple tags can be provided with comma separated strings. Use\
        \ tag1, tag2, tag3 for testing.
      operationId: getViewpointsByID
      parameters:
      - name: ids
        in: query
        description: ids
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Viewpoint'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Viewpoint'
        "400":
          description: Invalid
      deprecated: true
      security:
      - grove_auth:
        - write:viewpoints
        - read:viewpoints
      x-swagger-router-controller: Viewpoint
    put:
      tags:
      - viewpoint
      summary: Update a viewpoint
      operationId: updateViewpoint
      requestBody:
        $ref: '#/components/requestBodies/Viewpoint'
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Viewpoint
    post:
      tags:
      - viewpoint
      summary: Add a new viewpoint
      operationId: addViewpoint
      requestBody:
        $ref: '#/components/requestBodies/Viewpoint'
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Viewpoint
  /leader:
    get:
      tags:
      - leader
      summary: Finds leaders by id
      description: Muliple tags can be provided with comma separated strings. Use\
        \ tag1, tag2, tag3 for testing.
      operationId: getLeadersByID
      parameters:
      - name: ids
        in: query
        description: ids
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Leader'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Leader'
        "400":
          description: Invalid
      deprecated: true
      security:
      - grove_auth:
        - write:viewpoints
        - read:viewpoints
      x-swagger-router-controller: Leader
    put:
      tags:
      - leader
      summary: Update a leader
      operationId: updateLeader
      requestBody:
        $ref: '#/components/requestBodies/Leader'
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Leader
    post:
      tags:
      - leader
      summary: Add a new leader
      operationId: addLeader
      requestBody:
        $ref: '#/components/requestBodies/Leader'
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Leader
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: User
  /user/login:
    get:
      tags:
      - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
            application/xml:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
      x-swagger-router-controller: User
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: User
  /user/{username}:
    get:
      tags:
      - user
      summary: Get user by user name
      operationId: getUserByName
      parameters:
      - name: username
        in: path
        description: The name that needs to be fetched. Use user1 for testing.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
      x-swagger-router-controller: User
    put:
      tags:
      - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
      - name: username
        in: path
        description: name that need to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "400":
          description: Invalid user supplied
        "404":
          description: User not found
      x-swagger-router-controller: User
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
      - name: username
        in: path
        description: The name that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
      x-swagger-router-controller: User
components:
  schemas:
    Viewpoint:
      type: object
      properties:
        id:
          type: integer
          format: int64
        num_agrees:
          type: integer
          format: int32
        summary_text:
          type: string
        author:
          type: string
      example:
        author: author
        summary_text: summary_text
        id: 6
        num_agrees: 1
      xml:
        name: Viewpoint
    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        viewpoints:
          type: array
          items:
            $ref: '#/components/schemas/Viewpoint'
        organization:
          type: string
        pop_estimate:
          type: array
          items:
            type: number
            format: float
        leader_actions:
          type: array
          items:
            $ref: '#/components/schemas/Leader_Action'
      example:
        organization: organization
        name: name
        id: 0
        viewpoints:
        - author: author
          summary_text: summary_text
          id: 6
          num_agrees: 1
        - author: author
          summary_text: summary_text
          id: 6
          num_agrees: 1
        leader_actions:
        - leader: leader
          bill: bill
          id: 5
          vote: "yes"
        - leader: leader
          bill: bill
          id: 5
          vote: "yes"
        pop_estimate:
        - 5.962134
        - 5.962134
      xml:
        name: Issue
    Organization:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/Leader_Action'
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'
        leaders:
          type: array
          items:
            $ref: '#/components/schemas/Leader'
      example:
        members:
        - leader: leader
          bill: bill
          id: 5
          vote: "yes"
        - leader: leader
          bill: bill
          id: 5
          vote: "yes"
        name: name
        leaders:
        - last_name: last_name
          div_index: 6.0274563
          id: 0
          title: title
          first_name: first_name
          actions:
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
        - last_name: last_name
          div_index: 6.0274563
          id: 0
          title: title
          first_name: first_name
          actions:
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
        id: 6
        issues:
        - organization: organization
          name: name
          id: 0
          viewpoints:
          - author: author
            summary_text: summary_text
            id: 6
            num_agrees: 1
          - author: author
            summary_text: summary_text
            id: 6
            num_agrees: 1
          leader_actions:
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          pop_estimate:
          - 5.962134
          - 5.962134
        - organization: organization
          name: name
          id: 0
          viewpoints:
          - author: author
            summary_text: summary_text
            id: 6
            num_agrees: 1
          - author: author
            summary_text: summary_text
            id: 6
            num_agrees: 1
          leader_actions:
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          pop_estimate:
          - 5.962134
          - 5.962134
      xml:
        name: Leader
    Leader:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        title:
          type: string
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Leader_Action'
        div_index:
          type: number
          format: float
      example:
        last_name: last_name
        div_index: 6.0274563
        id: 0
        title: title
        first_name: first_name
        actions:
        - leader: leader
          bill: bill
          id: 5
          vote: "yes"
        - leader: leader
          bill: bill
          id: 5
          vote: "yes"
      xml:
        name: Leader
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
        phone:
          type: string
        viewpoints:
          type: array
          items:
            $ref: '#/components/schemas/Viewpoint'
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
        demographics:
          type: array
          items:
            oneOf:
            - type: string
            - type: integer
      example:
        firstName: firstName
        lastName: lastName
        password: ""
        phone: phone
        organizations:
        - members:
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          name: name
          leaders:
          - last_name: last_name
            div_index: 6.0274563
            id: 0
            title: title
            first_name: first_name
            actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
          - last_name: last_name
            div_index: 6.0274563
            id: 0
            title: title
            first_name: first_name
            actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
          id: 6
          issues:
          - organization: organization
            name: name
            id: 0
            viewpoints:
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            leader_actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            pop_estimate:
            - 5.962134
            - 5.962134
          - organization: organization
            name: name
            id: 0
            viewpoints:
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            leader_actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            pop_estimate:
            - 5.962134
            - 5.962134
        - members:
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          - leader: leader
            bill: bill
            id: 5
            vote: "yes"
          name: name
          leaders:
          - last_name: last_name
            div_index: 6.0274563
            id: 0
            title: title
            first_name: first_name
            actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
          - last_name: last_name
            div_index: 6.0274563
            id: 0
            title: title
            first_name: first_name
            actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
          id: 6
          issues:
          - organization: organization
            name: name
            id: 0
            viewpoints:
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            leader_actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            pop_estimate:
            - 5.962134
            - 5.962134
          - organization: organization
            name: name
            id: 0
            viewpoints:
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            - author: author
              summary_text: summary_text
              id: 6
              num_agrees: 1
            leader_actions:
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            - leader: leader
              bill: bill
              id: 5
              vote: "yes"
            pop_estimate:
            - 5.962134
            - 5.962134
        id: 0
        viewpoints:
        - author: author
          summary_text: summary_text
          id: 6
          num_agrees: 1
        - author: author
          summary_text: summary_text
          id: 6
          num_agrees: 1
        email: email
        username: username
        demographics:
        - ""
        - ""
      xml:
        name: User
    Leader_Action:
      type: object
      properties:
        id:
          type: integer
          format: int64
        leader:
          type: string
        bill:
          type: string
        vote:
          type: string
          enum:
          - "yes"
          - "no"
          - abstain
      example:
        leader: leader
        bill: bill
        id: 5
        vote: "yes"
      xml:
        name: Leader_Action
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    Viewpoint:
      description: Viewpoint to be added to issue page
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Viewpoint'
        application/xml:
          schema:
            $ref: '#/components/schemas/Viewpoint'
      required: true
    Leader:
      description: Issue to be added to organization
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Leader'
        application/xml:
          schema:
            $ref: '#/components/schemas/Leader'
      required: true
    Issue:
      description: Issue to be added to organization
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Issue'
        application/xml:
          schema:
            $ref: '#/components/schemas/Issue'
      required: true
    Organization:
      description: Add organization
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Organization'
        application/xml:
          schema:
            $ref: '#/components/schemas/Organization'
      required: true
    Leader_Action:
      description: Leader action to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Leader_Action'
        application/xml:
          schema:
            $ref: '#/components/schemas/Leader_Action'
      required: true
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      required: true
  securitySchemes:
    grove_auth:
      type: oauth2
      flows:
        implicit:
          scopes:
            write:viewpoint: write viewpoints
            read:viewpoint: read viewpoints
    api_key:
      type: apiKey
      name: api_key
      in: header
